/**
 * @file    main.c
 * @brief   CAN Dashboard – application entry point.
 *
 * This file assumes the HAL peripheral handles (hcan1, huart1) are
 * declared and initialised by the CubeMX-generated code that lives
 * alongside this file. The .ioc configuration must have:
 *
 *   CAN1  – enabled, 500 kbps, normal mode
 *   USART1 – enabled, 115200-8N1, TX only (or TX+RX)
 *   SYS   – Timebase source: SysTick
 *
 * Simulation mode:
 *   When compiled with -DSIM_MODE (add to project C defines in
 *   CubeIDE: Project > Properties > C/C++ Build > Settings > MCU GCC
 *   Compiler > Preprocessor), the ECU SetData calls use a simple
 *   sine-wave profile so you can watch the dashboard values change
 *   without real sensors.
 */

#include "main.h"
#include "ecu1.h"
#include "ecu2.h"
#include "ecu3_dashboard.h"
#include <math.h>   /* sinf – only used in SIM_MODE */

/* ─── HAL handles (generated by CubeMX) ─────────────────────── */
CAN_HandleTypeDef  hcan1;
UART_HandleTypeDef huart1;

/* ─── Private prototypes ─────────────────────────────────────── */
static void SystemClock_Config(void);
static void MX_GPIO_Init      (void);
static void MX_CAN1_Init      (void);
static void MX_USART1_UART_Init(void);

#ifdef SIM_MODE
static void SimUpdate(void);
static uint32_t s_sim_tick = 0U;
#endif

/* ─── main ───────────────────────────────────────────────────── */
int main(void)
{
    /* 1. HAL init + system clock */
    HAL_Init();
    SystemClock_Config();

    /* 2. Peripheral init (generated by CubeMX) */
    MX_GPIO_Init();
    MX_CAN1_Init();
    MX_USART1_UART_Init();

    /* 3. Application init */
    ECU3_Init();   /* configures filters, enables CAN notifications,
                      starts the CAN peripheral                     */

    /* 4. Main loop */
    while (1)
    {
#ifdef SIM_MODE
        SimUpdate();          /* feed synthetic sensor values        */
#endif
        ECU1_Task();          /* transmit vehicle status @ 100 ms    */
        ECU2_Task();          /* transmit engine data    @ 100 ms    */
        ECU3_Task();          /* print dashboard via UART @ 500 ms   */
    }
}

/* ─── SIM_MODE synthetic data generator ─────────────────────── */
#ifdef SIM_MODE
/**
 * @brief  Produce smoothly varying sensor values for bench testing.
 *         Called every main-loop iteration (~every few µs), but
 *         uses a 200 ms gate to avoid updating faster than needed.
 */
static void SimUpdate(void)
{
    static uint32_t last = 0U;
    if ((HAL_GetTick() - last) < 200U) return;
    last = HAL_GetTick();

    /* Oscillate speed 40–120 km/h over a 20-second period */
    float t     = (float)HAL_GetTick() / 1000.0f;
    float speed = 80.0f + 40.0f * sinf(t * 0.314f);   /* 0.1 Hz */
    float rpm   = 1000.0f + speed * 25.0f;
    uint8_t gear = (speed < 30) ? 1 :
                   (speed < 50) ? 2 :
                   (speed < 70) ? 3 :
                   (speed < 90) ? 4 : 5;

    /* Alternate indicator every 5 s */
    uint8_t ind = ((HAL_GetTick() / 5000U) % 3U);

    ECU1_SetData((uint16_t)speed, 88U, ind);
    ECU2_SetData((uint16_t)rpm,   gear);

    s_sim_tick++;
}
#endif /* SIM_MODE */

/* ─── Error handler (called by HAL on fatal errors) ─────────── */
void Error_Handler(void)
{
    __disable_irq();
    while (1) { /* trap */ }
}

/* ─────────────────────────────────────────────────────────────
   The functions below (SystemClock_Config, MX_*_Init) are
   normally auto-generated by STM32CubeMX from the .ioc file.
   The bodies shown here are representative for STM32F429 @180 MHz
   with CAN1 at 500 kbps and USART1 at 115200 baud.
   ───────────────────────────────────────────────────────────── */

static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM       = 8U;
    osc.PLL.PLLN       = 360U;
    osc.PLL.PLLP       = RCC_PLLP_DIV2;
    osc.PLL.PLLQ       = 7U;

    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    if (HAL_PWREx_EnableOverDrive() != HAL_OK) Error_Handler();

    clk.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                       | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;   /* 45 MHz – CAN lives here */
    clk.APB2CLKDivider = RCC_HCLK_DIV2;

    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5) != HAL_OK) Error_Handler();
}

static void MX_CAN1_Init(void)
{
    /* 500 kbps @ APB1 = 45 MHz:
       Prescaler=5, BS1=TQ6, BS2=TQ8  → 45MHz/(5*(1+6+8))=600kbps
       Use prescaler=9 for exactly 500 kbps with BS1=6, BS2=2        */
    hcan1.Instance                  = CAN1;
    hcan1.Init.Prescaler            = 9U;
    hcan1.Init.Mode                 = CAN_MODE_NORMAL;
    hcan1.Init.SyncJumpWidth        = CAN_SJW_1TQ;
    hcan1.Init.TimeSeg1             = CAN_BS1_6TQ;
    hcan1.Init.TimeSeg2             = CAN_BS2_2TQ;
    hcan1.Init.TimeTriggeredMode    = DISABLE;
    hcan1.Init.AutoBusOff           = ENABLE;
    hcan1.Init.AutoWakeUp           = DISABLE;
    hcan1.Init.AutoRetransmission   = ENABLE;
    hcan1.Init.ReceiveFifoLocked    = DISABLE;
    hcan1.Init.TransmitFifoPriority = DISABLE;

    if (HAL_CAN_Init(&hcan1) != HAL_OK) Error_Handler();
}

static void MX_USART1_UART_Init(void)
{
    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200U;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart1) != HAL_OK) Error_Handler();
}

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    /* CAN1: PD0=RX  PD1=TX (AF9)  */
    /* USART1: PA9=TX  PA10=RX (AF7) */
    /* GPIO configuration is normally generated by CubeMX */
}
